ClinkDevRoot:
  #########################################################################################################
  ClinkFeb[:]:
    ###################
    ClinkTop:
    ###################
      PllConfig[:]: '25MHz'
      ###################
      Ch[0]:
        LinkMode: Base
        DataMode: 12Bit
        FrameMode: Frame
        TapCount: 2
        DataEn: True
        Blowoff: False
        BaudRate: 9600 # units of bps
        SerThrottle: 30000 # (30ms x 1us throttle rate) = 10000
        SwControlValue: 0x0
        SwControlEn: 0x0
        ###################
        UartUp900cl12b: # UP-900CL-12B
          SM: 'f'
    ###################
    TrigCtrl[0]:
      EnableTrig: True
      InvCC: True # Active LOW Pulse
      TrigMap: ChA # ChA = pgpTrigger(0)
      TrigPulseWidth: 100.0 # units of us
      TrigMask: 0x2 # CC2 trigger
  #########################################################################################################
